### PR TITLE
Create Strings for zh-rCN

### PR DESCRIPTION
**Pull request by sr093906**

### CODE REVIEW

**Comment by berdosi** [comment]
Thank you for your work !
While checking it (through Google Translate), it occurred to me that this line seems to be referring to the Share button:
        后，你可以用“分享“按钮导出结果。
It was already wrong in my English original, and your work made me notice this issue, thanks for that, too.
I fixed the English wording in 3673ace to "you can export the results through the menu". If you wish, I delay merging the PR once the wording is changed in Chinese as well. Apologies for making you work twice.

**Comment by sr093906** [comment]
Done.

**Review by berdosi — APPROVED** [review]

**Comment by berdosi** [comment]
Merged, thanks again!

**Comment by sr093906** [comment]
Welcome.

**Pull request merged**
